version: '3.7'
networks:
  net1:

services:
  cassandra:
    image: "${CASSANDRA_IMAGE}"
    container_name: cassandra
    networks: [ "net1" ]
    environment:
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "DS_LICENSE=accept"
      - "CASSANDRA_DC=datacenter1"
      - "DC=datacenter1"
      - "LOCAL_JMX=no"
      - "JVM_EXTRA_OPTS=-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=7199"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
    ports:
      - "9042:9042"
      - "7199:7199"
      - "8081:8081"

  pulsar:
    image: "${PULSAR_IMAGE}"
    container_name: pulsar
    networks: [ "net1" ]
    environment:
      - "PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - '8080:8080'
      - '6650:6650'
    command: /bin/bash -c "bin/pulsar standalone -nss"
